apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

# make sure namespace exists
resources:
- namespace.yaml


helmCharts:
- name: airflow
  includeCRDs: false
  repo: https://airflow-helm.github.io/charts
  version: "8.8.0"
  releaseName: airflow-stable
  namespace: airflow
  valuesFile: sample-values-KubernetesExecutor.yaml
